on:
    push:

jobs:
    build-x86:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: DeterminateSystems/nix-installer-action@main
            - run: nix run .#x86
            - uses: actions/upload-artifact@v4
              with:
                  name: x86-img
                  path: main.raw
